CREATE TABLE EMPLOYEE( 	
    ID            				INTEGER NOT NULL,
    FIRSTNAME          			VARCHAR2(50) NOT NULL, 
    LASTNAME        			VARCHAR2(50) NOT NULL,
   CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID) 
 );
 

CREATE SEQUENCE employee_seq
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;


INSERT INTO EMPLOYEE VALUES (1, 'David', 'JOHNSON');
INSERT INTO EMPLOYEE VALUES (2, 'Larry', 'HOLMES');


select e1_0.id,e1_0.firstname,e1_0.lastname from employee e1_0;


